name: assignsix
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  sqflite: ^2.3.3+1
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  injectable: ^2.4.2
  go_router: ^14.2.1
  path: ^1.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.1
  freezed: ^2.5.2
  retrofit_generator: ^8.1.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  
flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/

  fonts:
    - family: Perpetua Titling MT
      fonts:
        - asset: assets/fonts/PerpetuaTitlingMTLight.ttf
          weight: 300
    - family: Bell MT
      fonts:
        - asset: assets/fonts/BellMT.ttf
          weight: 400
    - family: Ulagadi Sans
      fonts:
        - asset: assets/fonts/UlagadiSansLight.ttf
          weight: 300
        - asset: assets/fonts/UlagadiSans.ttf
          weight: 400
